volumes:
  redis-data:
    external: false

x-python-container: &python-container
  image: docker.io/library/python:3.12
  volumes:
    - ./:/opt/pitwall/
  depends_on:
    redis:
      condition: service_started
  command: sleep infinity
  env_file:
    - publish-dev.env

services:

  proxy:
    image: docker.io/library/nginx:alpine
    volumes:
      - ./mock-api/nginx-template/:/etc/nginx/templates/:ro
    depends_on:
      signalr:
        condition: service_started

  signalr:
    image: docker.io/library/python:3.12
    volumes:
      - ./mock-api/:/opt/
    env_file:
      - mock-api-dev.env
    command:
      - /bin/sh
      - -c
      - >
        cd /opt &&
        python -m pip install -r requirements.txt && 
        gunicorn -b 0.0.0.0:8000 --workers 1 --threads 64 --log-level debug --reload signalr:app
    healthcheck:
      test: curl --fail http://localhost:8000/ping

  redis:
    image: docker.io/redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
  
  race-control-publisher:
    <<: *python-container
    command: /opt/pitwall/entrypoint.sh publisher/race-control.py
  
  timing-publisher:
    <<: *python-container
    command: /opt/pitwall/entrypoint.sh publisher/timing.py
  
  pitlane-publisher:
    <<: *python-container
    command: /opt/pitwall/entrypoint.sh publisher/pitlane.py
  
  tyre-publisher:
    <<: *python-container
    command: /opt/pitwall/entrypoint.sh publisher/tyre.py

  telemetry-publisher:
    <<: *python-container
    command: /opt/pitwall/entrypoint.sh publisher/telemetry.py
  
  # radio-publisher:
  #   <<: *python-container
  #   command: /opt/pitwall/entrypoint.sh publisher/radio.py