build-pitwall-amd64-image:
  stage: build
  image: quay.io/podman/stable
  timeout: 3h
  retry: 2
  hooks:
    pre_get_sources_script:
      - umask 0022
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ( podman pull "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-amd64" &> /dev/hull ) || ( podman build -f build/pitwall.containerfile -t "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-amd64" . && podman push --retry=5 "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-amd64" )
  resource_group: build-pitwall-image-$CI_COMMIT_SHORT_SHA-amd64

build-pitwall-arm64-image:
  stage: build
  image: quay.io/podman/stable
  timeout: 3h
  retry: 2
  hooks:
    pre_get_sources_script:
      - umask 0022
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ( podman pull "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-arm64" &> /dev/hull ) || ( podman build -f build/pitwall.containerfile -t "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-arm64" . && podman push --retry=5 "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-arm64" )
  resource_group: build-pitwall-image-$CI_COMMIT_SHORT_SHA-arm64
  tags:
    - saas-linux-small-arm64