.container-image-release: &container-image-release
  stage: release
  image: quay.io/podman/stable
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - podman login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - podman pull "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-amd64"
    - podman pull "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-arm64"
    - podman tag "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-amd64" "$IMAGE_FULLNAME:$IMAGE_TAG-amd64"
    - podman tag "$CI_REGISTRY_IMAGE/pitwall:$CI_COMMIT_SHORT_SHA-arm64" "$IMAGE_FULLNAME:$IMAGE_TAG-arm64"
    - podman manifest create $IMAGE_FULLNAME:$IMAGE_TAG $IMAGE_FULLNAME:$IMAGE_TAG-amd64 $IMAGE_FULLNAME:$IMAGE_TAG-arm64
    - podman manifest push --all $IMAGE_FULLNAME:$IMAGE_TAG

gitlab-commit-image:
  <<: *container-image-release
  stage: build
  variables:
    REGISTRY_USER: "$CI_REGISTRY_USER"
    REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    REGISTRY: "$CI_REGISTRY"
    IMAGE_FULLNAME: "$CI_REGISTRY_IMAGE/pitwall"
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  needs:
    - job: build-pitwall-amd64-image
    - job: build-pitwall-arm64-image

dockerhub-tagged-image:
  <<: *container-image-release
  variables:
    REGISTRY_USER: "$DOCKER_USERNAME"
    REGISTRY_PASSWORD: "$DOCKER_TOKEN"
    REGISTRY: "docker.io"
    IMAGE_FULLNAME: "$DOCKER_REPO"
    IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG && $DOCKER_USERNAME && $DOCKER_TOKEN && $DOCKER_REPO

dockerhub-latest-image:
  <<: *container-image-release
  variables:
    REGISTRY_USER: "$DOCKER_USERNAME"
    REGISTRY_PASSWORD: "$DOCKER_TOKEN"
    REGISTRY: "docker.io"
    IMAGE_FULLNAME: "$DOCKER_REPO"
    IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_TAG && $DOCKER_USERNAME && $DOCKER_TOKEN && $DOCKER_REPO

dockerhub-nightly-image:
  <<: *container-image-release
  variables:
    REGISTRY_USER: "$DOCKER_USERNAME"
    REGISTRY_PASSWORD: "$DOCKER_TOKEN"
    REGISTRY: "docker.io"
    IMAGE_FULLNAME: "$DOCKER_REPO"
    IMAGE_TAG: nightly
  rules:
    - if: ( $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ) && $DOCKER_USERNAME && $DOCKER_TOKEN && $DOCKER_REPO
