test-discord-push-bod:
  stage: test
  image: $CI_REGISTRY_IMAGE/podman-compose:latest
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - podman system service -t 0 &
  script:
    - podman compose -f compose.ci.yaml up -d --quiet-pull
    - podman compose -f compose.ci.yaml wait race-control-publisher timing-publisher pitlane-publisher tyre-publisher telemetry-publisher radio-publisher
    - sleep 60
    - podman compose -f compose.ci.yaml down
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SESSION_LIST != 'None'
