test-discord-push-bod:
  stage: test
  image: $CI_REGISTRY_IMAGE/podman-compose:latest
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - podman system service -t 0 &
  script:
    - podman images
    - podman compose -f compose.ci.yaml pull
    - podman compose -f compose.ci.yaml up 
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SESSION_LIST != 'None'
